title: "Majestic Skin Clinic"


baseurl: "https://majesticskinclinic.com.au"


#defaultContentLanguage: "en"  #default en
#Content without language indicator will default to this language.
#defaultContentLanguageInSubdir: true #(false)
#Render the default content language in subdir, e.g. content/en/. The site root / will then redirect to /en/.

#disableAliases #(false) Will disable generation of alias redirects.
# removes rss feed, and taxonomy/categories folders
disableKinds: ["RSS", "taxonomy", "taxonomyTerm"]

enableRobotsTXT: true # (false)
# googleAnalytics: G-BG3JKCDCQL
googleAnalytics: UA-198438017-1
languageCode: "en-AU" # needs hyphen e.g. en-AU
# use {{ substr .Site.LanguageCode 0 2 }} to get the first 2 letters e.g. en
languageName: "English"
#disableLanguages

#log (false)
# logFile ("")
# Log File path (if set, logging enabled automatically).

# paginate: 7
# paginatePath #(“page”)
#pluralizeListTitles #(true)
# rssLimit: 10

markup:
  goldmark:
    #     extensions:
    #       definitionList: true
    #       footnote: true
    #       linkify: true
    #       strikethrough: true
    #       table: true
    #       taskList: true
    #       typographer: true
    #     parser:
    #       attribute:
    #         block: false
    #         title: true
    #       autoHeadingID: true
    #       autoHeadingIDType: github
    renderer:
      #       hardWraps: false
      unsafe: true #enable for inline html
#       xhtml: false

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5


taxonomies:
  series: series   # for fb og see also links

#[permalinks]
# blog: "/:title/"

imaging: 
  quality: 100

module:
  imports:
  - path: github.com/future-wd/hugo-image
  - path: github.com/future-wd/hugo-snipcart/v3
  - path: github.com/future-wd/hugo-svg-font






